# -*- coding: utf-8 -*-
"""Login application.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w4W5ljHlidjdBVp9uOPRB4KdEpXfsS3d
"""

#Getting New User input
first_name = input("Enter your first name: ")
last_name = input("Enter your last name: ")
email = input("Enter your email: ")
password = input("Enter your password: ")
age = input("Enter your age: ")
print("\n")

sentence = ""
condition = True
while condition: 
      #New password and email (for when logging in)
      email2 = input("Enter your email to sign in: ")
      password2 = input("Enter your password to sign in: ")

      #Making sure the first email and password will work with second email and password. 
      if email == email2 and password == password2:
       condition = False 
       newage = 0
  
        #checking if the age is actually a number
       if age.isdigit():
          newage = int(age)+ 1
       else:
        newage = age 
   
       sentence = "Welcome " + f"{first_name}" + " your age will be " + f"{newage} years " + "next year!" + "\n"
       print(sentence.upper())
       #break
      else: 
        print("try again \n")